# Site settings
title: Explore the Pittsburgh Procurement Process
description: >
  Click around to explore the way that procurement is 
  done in the City of Pittsburgh. Learn more about when an RFP is 
  generated and sent out, when the explanatory process is used, and more!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  codeforamerica

# Build settings
markdown: kramdown
